<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoffeeCard.Library\CoffeeCard.Library.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>
</Project>
