name: Deploy to prd

on:
  release:
    types: [published]

jobs:
  prd-deploy:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: prd
