name: Deploy to dev

on:
  push:
    branches:
      - main
      - feature/clean-old-tokens

jobs:
  dev-deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: dev
