name: Deploy

on:
  push:
    branches: [ develop, production ]

jobs:
  core-build:
    name: Build codebase
    uses: ./.github/workflows/core-build.yml
    with:
      push_image: true
    secrets: inherit
  
  infra-build:
    name: Build infrastructure
    uses: ./.github/workflows/infra-build.yml
    secrets: inherit

  sonarcloud:
    name: SonarCloud
    uses: ./.github/workflows/core-sonarcloud.yml
    secrets: inherit

  deploy_dev:
    name: Deploy dev
    if: github.ref_name == 'develop'
    needs: [ core-build, infra-build ]
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      environment: dev
      subscriptionId: analogio-dev

  deploy_prod:
    name: Deploy prd
    if: github.ref_name == 'production'
    needs: [ core-build, infra-build ]
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      environment: prd
      subscriptionId: analogio-prd