name: Deploy

on:
  push:
    branches: [ develop, production ]

jobs:
  core-build:
    name: Build codebase
    uses: ./.github/workflows/core-build.yml
    with:
      push_image: true
    secrets: inherit
  
  infra-build:
    name: Build infrastructure
    uses: ./.github/workflows/infra-build.yml
    secrets: inherit

  infra-deploy:
    name: Deploy infrastructure
    uses: ./.github/workflows/infra-deploy.yml
    needs: [core-build, infra-build]
    secrets: inherit

  core-deploy:
    name: Deploy analog-core
    uses: ./.github/workflows/core-deploy.yml
    needs: infra-deploy
    secrets: inherit