name: Deploy to dev

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: dev
