name: Deploy to dev

on:
    push:
        branches:
            - develop

jobs:
    dev-deploy:
        uses: ./.github/actions/deploy.yml
        secrets: inherit
        with:
            environment: dev
            subscriptionId: analogio-dev
    