name: Deploy to Azure

on:
  push:
    branches: [develop, production, feature/azure-deploy, pr/jra/iac]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      push-image: true

  infra-deploy:
    uses: ./.github/workflows/infra-deploy.yml
    needs: build
    secrets: inherit

  core-deploy:
    uses: ./.github/workflows/core-deploy.yml
    needs: infra-deploy
    secrets: inherit