name: Build and push Docker container

on:
  push:
    branches: [ develop, production ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set branch name as env var
        id: vars
        run: |
          trimmed=$(echo ${GITHUB_REF#refs/*/} | tr "/" "-")
          echo ::set-output name=branchName::$trimmed
      - name: Print branch name
        run: |
          echo ${{ steps.vars.outputs.branchName }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          context: coffeecard/
          file: coffeecard/CoffeeCard.WebApi/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 
            ghcr.io/analogio/coffeecard-api:${{ steps.vars.outputs.branchName }}