name: Build and test solution

on:
  pull_request:
    branches: [ develop, production ]

  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Create an empty certificate file since it it a build dependency
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "coffeecard/CoffeeCard.WebApi/www.analogio.dk.pfx"
        FILE_DATA: "empty file"
    # Create an empty appsettings.json file since it it a build dependency
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "coffeecard/CoffeeCard.Console.Refund/appsettings.json"
        FILE_DATA: "empty file"
    # Create an empty certificate file since it it a build dependency
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "coffeecard/CoffeeCard.Console.Refund/www.analogio.dk.pfx"
        FILE_DATA: "empty file"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 3.1.x
    - name: Build CoffeeCard solution
      run: dotnet build coffeecard/
    - name: Run tests
      run: dotnet test coffeecard/
