name: Deploy ARM template

on:
  workflow_call:

jobs:
  deploy_dev:
    name: Deploy to dev
    uses: ./.github/workflows/infra-template-deploy.yml
    secrets: inherit
    with:
      environment: dev
      subscriptionId: analogio-dev

  deploy_prod:
    name: Deploy to prod
    if: github.ref_name == 'production'
    uses: ./.github/workflows/infra-template-deploy.yml
    secrets: inherit
    with:
      environment: prd
      subscriptionId: analogio-prd
