name: Template for deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: "The environment to deploy to"
        default: "dev"
      subscriptionId:
        type: string
        required: true
        description: "The Azure subscription ID to deploy to"
        default: "analogio-dev"

jobs:
  deploy:
    name: Deploy ARM template
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.AZURE_SUBSCRIPTION_URL }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: arm

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ inputs.subscriptionId }}
          scope: subscription
          region: "West Europe"
          template: azuredeploy.json
          parameters: "environment=${{ inputs.environment }}"
          deploymentName: "azuredeploy-${{github.run_number}}"
          failOnStdErr: true
