name: Scale up app service plan

on:
  # schedule:
  #   - cron: "15 5 * * 1-5" # UTC Time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: prd

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upscale in hours
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az appservice plan update --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ vars.AZURE_APPSERVICE_PLAN_NAME }} --sku B2
